export const STATS_MAP = [
  "Health",
  "IncomingRepairs",
  "HazardProtection",
  "MarksmanRifleDamage",
  "HeadshotDamage",
  "DamageToArmor",
  "RepairSkills",
  "SkillDuration",
  "SkillHaste",
  "ShotgunDamage",
  "TotalArmor",
  "ArmorOnKill",
  "CriticalHitChance",
  "ExplosiveDamage",
  "StatusEffects",
  "PistolDamage",
  "Stability",
  "Accuracy",
  "AssaultRifleDamage",
  "ReloadSpeed",
  "ArmorRegeneration",
  "CriticalHitDamage",
  "SkillDamage",
  "WeaponDamage",
  "RifleDamage",
  "WeaponHandling",
  "LmgDamage",
  "AmmoCapacity",
  "ExplosiveResistance",
  "SmgDamage",
  "PulseResistance",
  "Talent",
  "MagazineSize",
  "SignatureWeaponDamage",
  "ShieldHealth",
  "RateOfFire",
  "DisruptResistance",
  "DamageToHealth",
  "HealthOnKill",
  "SkillHealth",
  "SkillEfficiency",
  "DamageToToc",
  "ScannerPulseHaste",
  "HealthDamage",
  "MeleeDamage",
] as const;

export const CORE_STATS = [
  'Armor',
  'WeaponDamage',
  'SkillTier',
] as const;

// types based on: https://stackoverflow.com/a/54061487/10300983
// TypeScript version 3.4 has introduced so-called **const contexts**, 
// which is a way to declare a tuple type as immutable and get the narrow literal type directl
export type IGearAttribute = typeof STATS_MAP[number] | '*';
export type ICoreAttribute = typeof CORE_STATS[number] | '*';