const mods = [
    'Critical Hit Chance',
    'Critical Hit Damage',
    'Headshot Damage',
    'Armor on Kill',
    'Incoming Repairs',
    'Protection from Elites',
    'Bleed Resistance',
    'Blind/Deaf Resistance',
    'Burn Resistance',
    'Disrupt Resistance',
    'Shock Resistance',
    'Repair Skills',
    'Skill Haste',
    'Skill Duration',
    'Disorient Resistance',
    'Ensnare Resistance',
    'Pulse Resistance',
]